### ISSUE TITLE
If the user refreshes on the login sso website it gets an error screen - Not working

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-App-Websites#109]
## Steps to replicate the issue

1. Log in to https://demo.staging.tonomy.foundation/
2. Click on Login with Tonomy ID Staging 
Following SSO page is opened
https://sso.staging.tonomy.foundation/login?payload=eyJyZXF1ZXN0cyI6WyJleUpoYkdjaU9pSkZVekkxTmtzdFVpSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKa2FXUTZhbmRyT21WNVNtcGpibGxwVDJsS2VscFhUbmROYWxVeVlYcEZhVXhEU25Ka1NHdHBUMmxLUmxGNVNYTkpibWRwVDJsS1JXTkdRVFZhV0dSYVkxUmFZVk14VG1sWFYxbDZZbXBOZGxJeVl6TlZXR2hKV214S1dXTXlSazlSVm1NelRWaFNURTFyVW5CaFZHUjZVRk5KYzBsdWEybFBhVXBQWkRKU2NVNUViSGhTVkdNMFRESktkV0pZY0ZWUFJXaDZXbnBhUjFWVVdsSk5WMDVHVTBob1QySnFVbWhTVnpGMlZtdFZNVkZYZUVwUVUwbHpTVzEwY0ZwRFNUWkpiRUpXVVd3NVRFMVdPREJsYmxaeFZHdDNORmRGWkU1aFJuQnFWVmR3TUZWdFJUQmFSekYzVDFoU1JsZFVSa3haVlZKV1RraGFlR050VWpOUmJYQXhXVzAwTlZkV1ozcGFNbFpzVm5sS09TSXNJbXAwYVNJNkltaDBkSEJ6T2k4dmRHOXViMjE1TG1admRXNWtZWFJwYjI0dmRtTXZhV1F2Tm1RM1pqZ3lZamc1Tm1NMFl6RXdZMlJsT0RjaUxDSnVZbVlpT2pFMk9EWTROalV4TlRRc0luWmpJanA3SWtCamIyNTBaWGgwSWpwYkltaDBkSEJ6T2k4dmQzZDNMbmN6TG05eVp5OHlNREU0TDJOeVpXUmxiblJwWVd4ekwzWXhJbDBzSW1OeVpXUmxiblJwWVd4VGRXSnFaV04wSWpwN0luQmhlV3h2WVdRaU9uc2lZMkZzYkdKaFkydFFZWFJvSWpvaUwyTmhiR3hpWVdOcklpd2liM0pwWjJsdUlqb2lhSFIwY0hNNkx5OWtaVzF2TG5OMFlXZHBibWN1ZEc5dWIyMTVMbVp2ZFc1a1lYUnBiMjRpTENKd2RXSnNhV05MWlhraU9pSlFWVUpmU3pGZk5IcDFhazVNT0ZoSFRXaGFZMUZxZEZKaE5HUnRjRGwwUlZreFMyRkVWVFIyY1hKa2QwSnFkV0p1T1ZsWU0yZGxaVmNpTENKeVlXNWtiMjFUZEhKcGJtY2lPaUk0TlRRMFltRmxaVGRqT1dVMU1EWXhNREE0WVRrMU9ETXhPV0l3TXpkbFptSXlORGd5WkdRNE16YzVOREpoTmpZNVltTmhPRE16WVRjNVpXUmxPRGd4SW4wc0luUjVjR1VpT2lKTWIyZHBibEpsY1hWbGMzUWlmU3dpZEhsd1pTSTZXeUpXWlhKcFptbGhZbXhsUTNKbFpHVnVkR2xoYkNJc0lsUnZibTl0ZVZabGNtbG1hV0ZpYkdWRGNtVmtaVzUwYVdGc1YybDBhRlI1Y0dVaVhYMTkuMVhyWGRwNjhUelR5SmpqOEF5MGVvXzV4a1FpRFl4bVBJTlZrNXRHWFdWeEdKU3hXbDd0RHV1dDZaUDZzUXRHRE9TMTJkcmpqdExZSGlDZU1RcmpCcndFIl19
4. Click on refresh button on the top left of the browser

## What do you expect to happen?
An error screen
## What actually happens
It is not going to error screen. Refer to the attached video.

## Your environment
1.	Tonomy ID – staging 

- Operating system: Android 13
- Tonomy ID version: 0.27.0

https://github.com/Tonomy-Foundation/Tonomy-App-Websites/assets/134924864/727fc7e3-1163-429f-aea0-543a5ed4b2f1

**Comment by theblockstalk** [comment]
This is expected due to new browser behaviour. If you copy the URL and then paste it in a new tab you will get the expected error.

**Comment by vemakoti** [comment]
I have tested in " incognito browser "  and I am not getting an error screen. Please refer to the attached video.
[Recording 2023-06-21 205844.zip](https://github.com/Tonomy-Foundation/Tonomy-App-Websites/files/11824009/Recording.2023-06-21.205844.zip)

**Comment by vemakoti** [comment]
I have also tested by copying the URL as mentioned by @theblockstalk,. In this case an error screen is coming as expected.
Please refer to the video.
[Recording 2023-06-21 210535.zip](https://github.com/Tonomy-Foundation/Tonomy-App-Websites/files/11824151/Recording.2023-06-21.210535.zip)
