### ISSUE TITLE
Tonomy Id- Demo app crashing If password has special characters during account creation

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-App-Websites#126]
## Steps to replicate the issue
Open the Tonomy ID Demo app. 
Click on Create Account button
Then provide username
Then provide password with special characters like £,€
## What do you expect to happen?
Either password is accepted or a warning is given
## What actually happens
App is crashing
## Your environment
1.	Tonomy ID – Demo

- Operating system: Android 13
- Tonomy ID version: Unknown/ not mentioned in google play

**Comment by theblockstalk** [comment]
let's drop this issue as we will be moving from password to passphrase
