### ISSUE TITLE
Tonomy ID Staging App - Option to create new account / login with existing account is missing after installation

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-App-Websites#133]
## Steps to replicate the issue
 1. Install Tonomy ID and open
 2. Open Tonomy ID
3. Create new account "jack" in Tonomy ID
4.  Click the Menu icon on the left corner of the home page
5. Logout of Tonomy ID

## What do you expect to happen?

- choose to create new account or login

## What actually happens

- Tonomy ID staging app is automatically logging
Note :- Tonomy ID staging app was installed on this device multiple times before

## Your environment
1.	Tonomy ID – Staging 

- Device: Samsung galaxy A13
- Operating system: Android 13
- Tonomy ID version: Unknown/ not mentioned in google play

**Comment by theblockstalk** [comment]
@vemakoti also tested on and could NOT replicate:
- samsung galaxy s9+
- Andriod version 10
