### ISSUE TITLE
Tonomy ID staging app menu is not working

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-App-Websites#134]
## Steps to replicate the issue

1. Open the Tonomy ID staging app
2. Login / create a new account
2. Click on menu icon on  left  top corner home page 
3. Click on items in the menu drawer

## What do you expect to happen?

- Menu is opened with options (Home, Settings or Logout ) to choose 

## What actually happens

- Menu icon is not responding 
- After repeatedly tapping on menu icon then it shows an error

## Your environment
1.	Tonomy ID – staging 

- Operating system: Android 13
- Tonomy ID version: Unknown/ not mentioned in google play
![menu icon](https://github.com/Tonomy-Foundation/Tonomy-App-Websites/assets/134924864/2790b71a-f511-4b03-8e6c-e059c2f2b68f)

**Comment by theblockstalk** [comment]
is this the same bug as https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/133?
@vemakoti

**Comment by vemakoti** [comment]
No jack both are different 
#133 about an option to create a new account in Tonomy id staging app
#134 about Menu icon in Tonomy id staging app after installation.

**Comment by theblockstalk** [comment]
cannot replicate
