### ISSUE TITLE
No warning /error when wrong combination of app and website used 

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-App-Websites#135]
## Steps to replicate the issue
 Install and open the Tonomy ID Demo app
Enter Username & Password
Open https://demo.staging.tonomy.foundation/
Click on “Login with Tonomy ID Staging“ 
Then click on Scan QR code with the Tonomy ID Demo app.
## What do you expect to happen?
Either Username & Password are accepted or a warning  is given
## What actually happens
Scan QR code is not working in Tonomy ID Demo app.
## Your environment
1.	Tonomy ID – staging 

- Operating system: Android 13
- Tonomy ID version: 0.39.0

**Comment by theblockstalk** [comment]
I think this is fixed as part of https://github.com/Tonomy-Foundation/Tonomy-App-Websites/issues/104

**Comment by vemakoti** [comment]
Retested and it is still not working @theblockstalk

**Comment by theblockstalk** [comment]
make sure you have the updated Staging up from the play store @vemakoti. Then let us know if still not working.

**Comment by vemakoti** [comment]
I have retested with above version and it is working as expected. 
![WhatsApp Image 2023-08-09 at 7 57 23 PM](https://github.com/Tonomy-Foundation/Tonomy-App-Websites/assets/134924864/f8704732-88f7-4188-8417-a9a814bbe5cd)
