### ISSUE TITLE
"User login into the demo website and send a bank transfer" is not working when it is right or left corner of the webpage

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-App-Websites#189]
**Steps to Replicate the Issue**
Log in to - https://demo.demo.tonomy.foundation/user-home
Click on the Use case of signing transactions page
**What  do you expect to happen?**
The Use case of signing bank transactions page should be open
**What actually happens?**
The use case signing transactions  page is not working when it is in right and left corner. only it is working in middle of page

**Comment by sadiabbasi** [comment]
yess currently we added the redirect on the center image only.. so @theblockstalk do i need to add the links on side images too?

**Comment by theblockstalk** [comment]
so if user clicks on one of the left or right cards, that will slide that card into the centre
