### ISSUE TITLE
"User login into the demo website and sign and validate a medical record " is not working when it is right or left corner of the webpage.

### ISSUE THREAD

**Issue by vemakoti** [Tonomy-Foundation/Tonomy-App-Websites#196]
**Steps to replicate the issue**
Log into:-  https://demo.demo.tonomy.foundation/user-home
Click  on the use case of signing a document

**What do you expect to happen?**
The use case of signing a document page should be open

**What happens?**
The use case of signing a document page needs to be fixed when it is in the right and left corner. Only it is working in the middle of the page.

**Comment by sadiabbasi** [comment]
it's already done
