### ISSUE TITLE
Logged in user is sent to connection screen if already logged into SSO website (UI)

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-App-Websites#23]
Acceptance criteria
- [ ] New screen that matches design https://www.figma.com/file/cvV48t0f7O2znT6QBxK0Zj/Tonomy-ID?node-id=3556-24806&t=Cr3fIlWplpkcGWHt-4
- [ ] if the user has already logged into the SSO app, then next time they make a login request on Demo, they are sent to the connection screen (above) instead of being sent to the QR code scanner
- [ ] after the user has scanned the QR code while the Login Request is being sent, this screen is shown

**Comment by sadiabbasi** [comment]
I tested it in staging it's already implemented
