### ISSUE TITLE
Add buttons to the sign transaction demo page

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-App-Websites#249]
Acceptance criteria

- [ ] Before a user makes a payment (Send payment button) they can choose which network to send on (same network, Hedera or Ethereum). this could be with multiple buttons
- [ ] For a wallet transaction, the web app should show some feedback while waiting for the user

**Comment by pavel-tonomy** [comment]
Desktop: https://www.figma.com/design/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?node-id=1280-1679&t=80E42HcRr0nru8RN-1

Mobile: https://www.figma.com/design/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?node-id=1736-2640&t=80E42HcRr0nru8RN-1

**Comment by theblockstalk** [comment]
see comments https://www.figma.com/design/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?node-id=1736-2639&t=PcRcBb0UZXfUExO8-4
