### ISSUE TITLE
Review and design the app explorer mechanism for Tonomy Apps

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-App-Websites#261]
All Tonomy Apps should be able to use an app explorer (inspired by Google) to switch easily to other Tonomy Apps:

Acceptance criteria:
- Review the existing design: https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=405-1339&mode=design&t=TDH2PfJL8EALrXo0-4t
- Apply a consistent and future proof design to the Demo and Developer Console apps with this functionality
- Create a logo for demo website

**Comment by pavel-tonomy** [comment]
I've imrpoved the current design for the web version with new icons and typography. Besides I created new logos for developer console and demo website, but it's still required to be discussed. I also created a solid component for the design system and made a new more user-friendly mobile version

https://www.figma.com/file/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?type=design&node-id=1647%3A2824&mode=design&t=4FkMlE5MVJMxxtPQ-1
