### ISSUE TITLE
Implement Ethereum transaction signing in demo app

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-App-Websites#290]
https://www.figma.com/design/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?node-id=1732-4744&t=8JVlATcP0VYCBLRp-4

Acceptance criteria:

- [x] implement transaction sign on EThereum for demo
- [x] works on mobile and desktop

**Comment by pavel-tonomy** [comment]
Design: https://www.figma.com/design/Aedi8DrZwwParsirLortGt/Tonomy-Demo-Website?node-id=1736-2639&t=KSE7w44QK2AA8zqq-1

**Comment by pavel-tonomy** [comment]
The WalletConnect QR code has been added to both flows
