### ISSUE TITLE
If the user refreshes on the SSO website during login, they are shown an error message

### ISSUE THREAD

**Issue by theblockstalk** [Tonomy-Foundation/Tonomy-App-Websites#57]
Acceptance criteria

- [ ] if the user refreshes the SSO website during the login (and hence invalidating the `location.referrer` which protects us for security reasons) then they are shown a warning popup which says "Login unsuccessful, please try again and do not refresh this website during login"
- [ ] when they close the popup, they are redirected back to the external website with an error payload in the URL saying the user refreshed

**Comment by Rebal67** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by Rebal67** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
