### ISSUE TITLE
fix route authentication demo APP 

### ISSUE THREAD

**Issue by Rebal67** [Tonomy-Foundation/Tonomy-App-Websites#85]
refactor route authentication by making each route able to be protected by guards

acceptance Criteria:

- [ ] all routes are available to navigate  via react navigation
- [ ] route can be protect by a guard
- [ ] global provider for logging out exist

reference:
https://github.com/remix-run/react-router/tree/dev/examples/auth

**Comment by theblockstalk** [comment]
1 points to previous sprint
2 to new sprint

**Comment by theblockstalk** [comment]
previous sprint: 1
new sprint: 1
